Feature/pokedex api
hex-g/hive-api pull request #11
Opened 2019-04-26 23:11 UTC by SamuelLevi

__( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩__

# New things:
- CRUD of student / pedagogue / user
- API tests

# Changes:
- 

# Removed:
-

__( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩__

2019-04-26 23:24 UTC, eiling requested changes
Put EOL at EOF
Remove unused dependencies

2019-04-26 23:35 UTC, eiling approved these changes

2019-04-27 07:30 UTC, manoger requested changes
Fiz algumas considerações referentes ao entendimento dos testes.
Por favor verifique a pertinência deles.

Em suma:
* Na minha opinião, a compreensão de "IsRetrieved" fica a cargo de métodos http GET.
Coisa da qual confunde quando colocado com outros métodos.
* Utilize "Provided"(ou sinônimos) para questões relacionadas ao fornecimento de parâmetros.
*  "TriedTo" pode ser talvez trocado por "AttemptTo". (nesse caso específico pode ser frescura minha)
# /╲/\( •̀ ω •́ )/\╱\
Boa dia

2019-04-27 07:30 UTC, manoger commented on pokedex/src/main/java/hive/pokedex/exception/EntityAlreadyExistsException.java
> +@ResponseStatus(code = HttpStatus.CONFLICT, reason = "Entity already registered, try again")
```suggestion
@ResponseStatus(code = HttpStatus.CONFLICT, reason = "Entity already registered")
```
"try again" da impressão de tentar novamente com os mesmos dados

2019-04-27 07:30 UTC, manoger commented on pokedex/src/main/java/hive/pokedex/exception/UsernameAlreadyExistsException.java
> +@ResponseStatus(code = HttpStatus.CONFLICT, reason = "Username already registered, try again")
```suggestion
@ResponseStatus(code = HttpStatus.CONFLICT, reason = "Username already registered, try register other username")
```
"try again" da impressão que deve tentar de novo com os mesmo dados.

2019-04-27 07:30 UTC, manoger commented on pokedex/src/test/java/hive/pokedex/controller/StudentControllerTest.java
> +  public void givenTriedToSaveStudent_whenNoStudentInfoRetrieved_then406IsReceived() throws Exception {
```suggestion
  public void givenAttemptToSaveStudent_whenNoStudentInfoIsProvided_then406IsReceived() throws Exception {
```

2019-04-27 07:30 UTC, manoger commented on pokedex/src/test/java/hive/pokedex/controller/StudentControllerTest.java
> +  public void givenTriedToSaveStudent_whenEmptyStudentInfoIsRetrieved_then406IsReceived() throws Exception {
```suggestion
  public void givenAttemptToSaveStudent_whenEmptyStudentInfoIsProvided_then406IsReceived() throws Exception {
```

2019-04-27 07:30 UTC, manoger commented on pokedex/src/test/java/hive/pokedex/controller/StudentControllerTest.java
> +  public void givenTriedToSaveStudent_whenStudentInfoOnlyWhiteSpacesIsRetrieved_then406IsReceived() throws Exception {
```suggestion
  public void givenAttemptToSaveStudent_whenOnlyWhiteSpacesIsProvidedAsStudentInfo_then406IsReceived() throws Exception {
```

2019-04-27 07:30 UTC, manoger commented on pokedex/src/test/java/hive/pokedex/controller/PedagogueControllerTest.java
> +  public void givenTriedToSavePedagogue_whenEmptyPedagogueInfoIsRetrieved_then406IsReceived() throws Exception {
```suggestion
  public void givenAttemptToSavePedagogue_whenEmptyPedagogueInfoIsProvided_then406IsReceived() throws Exception {
```

2019-04-27 07:30 UTC, manoger commented on pokedex/src/test/java/hive/pokedex/controller/PedagogueControllerTest.java
> +  public void givenTriedToSavePedagogue_whenPedagogueInfoOnlyWhiteSpacesIsRetrieved_then406IsReceived() throws Exception {
```suggestion
  public void givenAttemptToSavePedagogue_whenPedagogueInfoOnlyWhiteSpacesIsProvided_then406IsReceived() throws Exception {
```

2019-04-27 07:30 UTC, manoger commented on pokedex/src/test/java/hive/pokedex/controller/PedagogueControllerTest.java
> +  public void givenPedagogueDoesNotExists_whenDeletePedagogueByIdIsRetrieved_then404IsReceived() throws Exception {
```suggestion
  public void givenPedagogueDoesNotExists_whenDeletePedagogueById_then404IsReceived() throws Exception {
```

2019-04-27 07:30 UTC, manoger commented on pokedex/src/test/java/hive/pokedex/controller/PedagogueControllerTest.java
> +  public void givenPedagogueExists_whenDeletePedagogueByIdIsRetrieved_then200IsReceived() throws Exception {
```suggestion
  public void givenPedagogueExists_whenDeletePedagogueById_then200IsReceived() throws Exception {
```

2019-04-27 07:30 UTC, manoger commented on pokedex/src/test/java/hive/pokedex/controller/StudentControllerTest.java
> +  public void givenStudentDoesNotExists_whenStudentUpdatedInfoIsRetrieved_then404IsReceived() throws Exception {
```suggestion
  public void givenStudentDoesNotExists_whenUpdateStudentInfo_then404IsReceived() throws Exception {
```

2019-04-27 07:30 UTC, manoger commented on pokedex/src/test/java/hive/pokedex/controller/StudentControllerTest.java
> +  public void givenStudentExists_whenStudentUpdatedInfoIsRetrieved_then200IsReceived() throws Exception {
```suggestion
  public void givenStudentExists_whenUpdateStudentInfo_then200IsReceived() throws Exception {
```

2019-04-27 07:30 UTC, manoger commented on pokedex/src/test/java/hive/pokedex/controller/StudentControllerTest.java
> +  public void givenTriedToSaveStudent_whenExistentStudentUsernameIsRetrieved_then409IsReceived() throws Exception {
```suggestion
  public void givenTriedToSaveStudent_whenStudentUsernameAlreadyExists_then409IsReceived() throws Exception {
```

2019-04-27 07:30 UTC, manoger commented on pokedex/src/test/java/hive/pokedex/controller/StudentControllerTest.java
> +  public void givenTriedToSaveStudent_whenExistentStudentRaIsRetrieved_then409IsReceived() throws Exception {
```suggestion
  public void givenTriedToSaveStudent_whenStudentRaAlreadyExists_then409IsReceived() throws Exception {
```

2019-04-27 07:30 UTC, manoger commented on pokedex/src/test/java/hive/pokedex/controller/StudentControllerTest.java
> +  public void givenStudentExists_whenDeleteStudentByIdIsRetrieved_then200IsReceived() throws Exception {
```suggestion
  public void givenStudentExists_whenDeleteStudentById_then200IsReceived() throws Exception {
```

2019-04-27 07:30 UTC, manoger commented on pokedex/src/test/java/hive/pokedex/controller/StudentControllerTest.java
> +  public void givenStudentDoesNotExists_whenDeleteStudentByIdIsRetrieved_then404IsReceived() throws Exception {
```suggestion
  public void givenStudentDoesNotExists_whenDeleteStudentById_then404IsReceived() throws Exception {
```

2019-04-27 07:30 UTC, manoger commented on pokedex/src/test/java/hive/pokedex/controller/UserControllerTest.java
> +  public void givenTriedToSaveUser_whenNoUserInfoRetrieved_then406IsReceived() throws Exception {
```suggestion
  public void givenTriedToSaveUser_whenNoUserInfoIsProvided_then406IsReceived() throws Exception {
```

2019-04-27 07:30 UTC, manoger commented on pokedex/src/test/java/hive/pokedex/controller/UserControllerTest.java
> +  public void givenTriedToSaveUser_whenEmptyUserInfoIsRetrieved_then406IsReceived() throws Exception {
```suggestion
  public void givenAttemptToSaveUser_whenEmptyUserInfoIsProvided_then406IsReceived() throws Exception {
```

2019-04-27 07:30 UTC, manoger commented on pokedex/src/test/java/hive/pokedex/controller/UserControllerTest.java
> +  public void givenTriedToSaveUser_whenUserInfoOnlyWhiteSpacesIsRetrieved_then406IsReceived() throws Exception {
```suggestion
  public void givenAttemptToSaveUser_whenOnlyWhiteSpacesIsProvidedAsUserInfo_then406IsReceived() throws Exception {
```

2019-04-27 07:30 UTC, manoger commented on pokedex/src/test/java/hive/pokedex/controller/UserControllerTest.java
> +  public void givenUserDoesNotExists_whenDeleteUserByIdIsRetrieved_then404IsReceived() throws Exception {
```suggestion
  public void givenUserDoesNotExists_whenDeleteUserById_then404IsReceived() throws Exception {
```

2019-04-27 07:30 UTC, manoger commented on pokedex/src/test/java/hive/pokedex/controller/UserControllerTest.java
> +  public void givenUserExists_whenDeleteUserByIdIsRetrieved_then200IsReceived() throws Exception {
```suggestion
  public void givenUserExists_whenDeleteUserById_then200IsReceived() throws Exception {
```

2019-04-28 02:59 UTC, manoger approved these changes

2019-04-28 03:03 UTC, merged